export const Types = {
	mutations: {
		ARTICLES_REQUESTED: 'ARTICLES_REQUESTED',
		ARTICLES_SUCCEEDED: 'fetchArticles',
		ARTICLES_FAILED: 'ARTICLES_FAILED',
		ARTICLES_CANCELED: 'ARTICLES_CANCELED',
		ARTICLE_ADD_REQUESTED: 'ARTICLE_ADD_REQUESTED',
		ARTICLE_ADD_SUCCEDED: 'ARTICLE_ADD_SUCCEDED',
		ARTICLE_ADD_FAILED: 'ARTICLE_ADD_FAILED',
	},
	actions: {
		ARTICLES_LOAD: 'fetchArticles',
		ARTICLES_LOAD_CANCEL: 'cancelLoading'
	},
	request_status: {
		REQUESTED: 'REQUESTED',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED'
	}
}